"""initial_schema

Revision ID: 09b36d7bea8c
Revises: 
Create Date: 2026-10-04 10:05:13.125965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b36d7bea8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name_uz', sa.String(length=100), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('standard_unit', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crops_slug'), ['slug'], unique=True)

    op.create_table('regions',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_uz', sa.String(length=100), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'BUYER', 'DRIVER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('buyer_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('buyer_type', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buyer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyer_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('districts',
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('name_uz', sa.String(length=100), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_districts_region_id'), ['region_id'], unique=False)

    op.create_table('driver_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_trips', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('market_prices',
    sa.Column('crop_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=False),
    sa.Column('market_name', sa.String(length=120), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_prices_crop_id'), ['crop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_prices_recorded_date'), ['recorded_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_prices_region_id'), ['region_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('price_alerts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('crop_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_alerts_crop_id'), ['crop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('demand_requests',
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('crop_id', sa.String(length=36), nullable=False),
    sa.Column('destination_district_id', sa.String(length=36), nullable=True),
    sa.Column('target_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'FULFILLED', 'EXPIRED', 'CANCELLED', name='demandstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['destination_district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demand_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_requests_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_requests_crop_id'), ['crop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demand_requests_status'), ['status'], unique=False)

    op.create_table('farmer_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('region_id', sa.String(length=36), nullable=True),
    sa.Column('district_id', sa.String(length=36), nullable=True),
    sa.Column('farm_name', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('total_deals', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('listings',
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('crop_id', sa.String(length=36), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_order_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quality_grade', sa.String(length=20), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'RESERVED', 'SOLD', 'EXPIRED', name='listingstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_crop_id'), ['crop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_farmer_id'), ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    op.create_table('vehicles',
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('plate_number', sa.String(length=30), nullable=False),
    sa.Column('capacity_tons', sa.Float(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('is_refrigerated', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_driver_id'), ['driver_id'], unique=False)

    op.create_table('listing_photos',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_photos_listing_id'), ['listing_id'], unique=False)

    op.create_table('offers',
    sa.Column('demand_id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('offered_price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('offered_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='offerstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demand_requests.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_demand_id'), ['demand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_farmer_id'), ['farmer_id'], unique=False)

    op.create_table('orders',
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('offer_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_product_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'CONFIRMED', 'PAID_ESCROW', 'PICKED_UP', 'DELIVERED', 'COMPLETED', 'DISPUTED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('pickup_code', sa.String(length=10), nullable=True),
    sa.Column('delivery_code', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('delivery_jobs',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('pickup_district_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_district_id', sa.String(length=36), nullable=True),
    sa.Column('proposed_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('agreed_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('pickup_proof_url', sa.String(length=500), nullable=True),
    sa.Column('delivery_proof_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['pickup_district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_jobs_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_jobs_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_delivery_jobs_status'), ['status'], unique=False)

    op.create_table('disputes',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('raised_by', sa.String(length=36), nullable=False),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_urls', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPENED', 'UNDER_REVIEW', 'RESOLVED_RELEASE', 'RESOLVED_REFUND', 'CANCELLED', name='disputestatus'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disputes_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_raised_by'), ['raised_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_status'), ['status'], unique=False)

    op.create_table('escrow_ledger',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'HOLD', 'RELEASE', 'REFUND', 'FEE', name='escrowtxtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_tx_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='escrowtxstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escrow_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escrow_ledger_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escrow_ledger_provider_tx_id'), ['provider_tx_id'], unique=False)

    op.create_table('order_events',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('triggered_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_events_order_id'), ['order_id'], unique=False)

    op.create_table('payments',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('invoice_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)

    op.create_table('reviews',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('reviewee_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewee_id'), ['reviewee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewer_id'), ['reviewer_id'], unique=False)

    op.create_table('delivery_bids',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('bid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='bidstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['delivery_jobs.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_bids_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_bids_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_bids_job_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_bids_driver_id'))

    op.drop_table('delivery_bids')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_reviewee_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_order_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))

    op.drop_table('payments')
    with op.batch_alter_table('order_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_events_order_id'))

    op.drop_table('order_events')
    with op.batch_alter_table('escrow_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escrow_ledger_provider_tx_id'))
        batch_op.drop_index(batch_op.f('ix_escrow_ledger_order_id'))

    op.drop_table('escrow_ledger')
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disputes_status'))
        batch_op.drop_index(batch_op.f('ix_disputes_raised_by'))
        batch_op.drop_index(batch_op.f('ix_disputes_order_id'))

    op.drop_table('disputes')
    with op.batch_alter_table('delivery_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_delivery_jobs_order_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_jobs_driver_id'))

    op.drop_table('delivery_jobs')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_seller_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_orders_buyer_id'))

    op.drop_table('orders')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_offers_demand_id'))

    op.drop_table('offers')
    with op.batch_alter_table('listing_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_photos_listing_id'))

    op.drop_table('listing_photos')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_driver_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_index(batch_op.f('ix_listings_farmer_id'))
        batch_op.drop_index(batch_op.f('ix_listings_district_id'))
        batch_op.drop_index(batch_op.f('ix_listings_crop_id'))

    op.drop_table('listings')
    with op.batch_alter_table('farmer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_profiles_user_id'))

    op.drop_table('farmer_profiles')
    with op.batch_alter_table('demand_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_requests_status'))
        batch_op.drop_index(batch_op.f('ix_demand_requests_crop_id'))
        batch_op.drop_index(batch_op.f('ix_demand_requests_buyer_id'))

    op.drop_table('demand_requests')
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_price_alerts_crop_id'))

    op.drop_table('price_alerts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_prices_region_id'))
        batch_op.drop_index(batch_op.f('ix_market_prices_recorded_date'))
        batch_op.drop_index(batch_op.f('ix_market_prices_crop_id'))

    op.drop_table('market_prices')
    with op.batch_alter_table('driver_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_profiles_user_id'))

    op.drop_table('driver_profiles')
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_districts_region_id'))

    op.drop_table('districts')
    with op.batch_alter_table('buyer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buyer_profiles_user_id'))

    op.drop_table('buyer_profiles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regions_code'))

    op.drop_table('regions')
    with op.batch_alter_table('crops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crops_slug'))

    op.drop_table('crops')
    # ### end Alembic commands ###
